# data
data:
  instruct_data: "/home/admin/am_hackathon/mistral-finetune/data/dataset.jsonl"  # Fill
  data: ""  # Optionally fill with pretraining data 
  eval_instruct_data: "/home/admin/am_hackathon/mistral_finetune/mistral-finetune/data/eval_dataset.jsonl"  # Optionally fill

# model
model_id_or_path: "/home/admin/instruct/"  # Change to downloaded path
lora:
  rank: 64

# optim
seq_len: 2048
batch_size: 1
max_steps: 50000
optim:
  lr: 6.e-5
  weight_decay: 0.1
  pct_start: 0.05

# other
seed: 0
log_freq: 1
eval_freq: 100
no_eval: False
ckpt_freq: 100

save_adapters: True  # save only trained LoRA adapters. Set to `False` to merge LoRA adapter into the base model and save full fine-tuned model

run_dir: "run"  # Fill

wandb:
  project: "run" # your wandb project name
  run_name: "" # your wandb run name
  key: "" # your wandb api key
  offline: False
